---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    undistro.io: undistro
  name: undistro-controller-manager
  namespace: undistro-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    undistro.io: undistro
  name: undistro-leader-election-role
  namespace: undistro-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    undistro.io: undistro
  name: undistro-manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    undistro.io: undistro
  name: undistro-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    undistro.io: undistro
  name: undistro-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    undistro.io: undistro
  name: undistro-leader-election-rolebinding
  namespace: undistro-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: undistro-leader-election-role
subjects:
- kind: ServiceAccount
  name: undistro-controller-manager
  namespace: undistro-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    undistro.io: undistro
  name: undistro-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: undistro-manager-role
subjects:
- kind: ServiceAccount
  name: undistro-controller-manager
  namespace: undistro-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    undistro.io: undistro
  name: undistro-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: undistro-proxy-role
subjects:
- kind: ServiceAccount
  name: undistro-controller-manager
  namespace: undistro-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    undistro.io: undistro
  name: undistro-controller-manager-metrics-service
  namespace: undistro-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: controller-manager
    undistro.io: undistro
---
apiVersion: v1
kind: Service
metadata:
  labels:
    undistro.io: undistro
  name: undistro-webhook-service
  namespace: undistro-system
spec:
  ports:
  - name: webhook-server
    port: 443
    targetPort: 9443
  - name: undistro-server
    port: 2020
    targetPort: 2020
  selector:
    control-plane: controller-manager
    undistro.io: undistro
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
    undistro.io: undistro
  name: undistro-controller-manager
  namespace: undistro-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      undistro.io: undistro
  template:
    metadata:
      labels:
        control-plane: controller-manager
        undistro.io: undistro
    spec:
      containers:
      - args:
        - --v=2
        command:
        - /manager
        image: "{{ .Values.global.undistroRepository}}/undistro:{{ .Values.global.undistroVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 2020
          name: undistro-server
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
{{- with .Values.resources }}
        resources:
{{ toYaml . | indent 10 }}
{{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=4
        image: registry.undistro.io/gcr/kubebuilder/kube-rbac-proxy:v0.8.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
      serviceAccountName: undistro-controller-manager
      terminationGracePeriodSeconds: 60
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
      - configMap:
          name: undistro-manager-config
        name: manager-config
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    undistro.io: undistro
  name: undistro-selfsigned-issuer
  namespace: undistro-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    undistro.io: undistro
  name: undistro-serving-cert
  namespace: undistro-system
spec:
  dnsNames:
  - undistro-webhook-service.undistro-system.svc
  - undistro-webhook-service.undistro-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: undistro-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: undistro-system/undistro-serving-cert
  labels:
    undistro.io: undistro
  name: undistro-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: undistro-webhook-service
      namespace: undistro-system
      path: /mutate-app-undistro-io-v1alpha1-cluster
  failurePolicy: Fail
  name: mcluster.undistro.io
  rules:
  - apiGroups:
    - app.undistro.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: undistro-webhook-service
      namespace: undistro-system
      path: /mutate-app-undistro-io-v1alpha1-defaultpolicies
  failurePolicy: Fail
  name: mdefaultpolicies.undistro.io
  rules:
  - apiGroups:
    - app.undistro.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - defaultpolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: undistro-webhook-service
      namespace: undistro-system
      path: /mutate-app-undistro-io-v1alpha1-helmrelease
  failurePolicy: Fail
  name: mhelmrelease.undistro.io
  rules:
  - apiGroups:
    - app.undistro.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - helmreleases
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: undistro-system/undistro-serving-cert
  labels:
    undistro.io: undistro
  name: undistro-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: undistro-webhook-service
      namespace: undistro-system
      path: /validate-app-undistro-io-v1alpha1-cluster
  failurePolicy: Fail
  name: vcluster.undistro.io
  rules:
  - apiGroups:
    - app.undistro.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: undistro-webhook-service
      namespace: undistro-system
      path: /validate-app-undistro-io-v1alpha1-defaultpolicies
  failurePolicy: Fail
  name: vdefaultpolicies.undistro.io
  rules:
  - apiGroups:
    - app.undistro.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - defaultpolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: undistro-webhook-service
      namespace: undistro-system
      path: /validate-app-undistro-io-v1alpha1-helmrelease
  failurePolicy: Fail
  name: vhelmrelease.undistro.io
  rules:
  - apiGroups:
    - app.undistro.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - helmreleases
  sideEffects: None
