--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  labels: 
    app: {{ .Values.metadata.labels.app }}
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
rules: 
  - 
    apiGroups: 
      - ""
    resources: 
      - secrets
    verbs: 
      - create
      - get
      - list
      - patch
      - update
      - watch
      - delete
  - 
    apiGroups: 
      - config.supervisor.pinniped.dev
    resources: 
      - federationdomains
    verbs: 
      - get
      - list
      - watch
  - 
    apiGroups: 
      - config.supervisor.pinniped.dev
    resources: 
      - federationdomains/status
    verbs: 
      - get
      - patch
      - update
  - 
    apiGroups: 
      - idp.supervisor.pinniped.dev
    resources: 
      - oidcidentityproviders
    verbs: 
      - get
      - list
      - watch
  - 
    apiGroups: 
      - idp.supervisor.pinniped.dev
    resources: 
      - oidcidentityproviders/status
    verbs: 
      - get
      - patch
      - update
  - 
    apiGroups: 
      - idp.supervisor.pinniped.dev
    resources: 
      - ldapidentityproviders
    verbs: 
      - get
      - list
      - watch
  - 
    apiGroups: 
      - idp.supervisor.pinniped.dev
    resources: 
      - ldapidentityproviders/status
    verbs: 
      - get
      - patch
      - update
  - 
    apiGroups: 
      - ""
    resources: 
      - pods
    verbs: 
      - get
  - 
    apiGroups: 
      - apps
    resources: 
      - replicasets
      - deployments
    verbs: 
      - get
