apiVersion: v1
kind: Service
metadata:
  name: pinniped-supervisor-clusterip
  namespace: undistro-system
  labels:
    app: pinniped-supervisor
  annotations:
    kapp.k14s.io/disable-default-label-scoping-rules: ""
spec:
  type: ClusterIP
  selector:
    deployment.pinniped.dev: supervisor
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
