---
apiVersion: app.undistro.io/v1alpha1
kind: Cluster
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  annotations:
    undistro.io/cluster-autoscaler: ""
spec:
  kubernetesVersion: {{.K8sVersion}}
  controlPlane:
    replicas: 3
    machineType: m1.medium
  workers:
    - replicas: 2
      machineType:  m1.medium
    - replicas: 2
      infraNode: true
      machineType:  m1.medium
  infrastructureProvider:
    name: openstack
    {{if .SSHKey}}
    sshKey: {{.SSHKey}}
    {{end}}
    flavor: openstack
    extraConfiguration: {{.CloudsFile}}
{{- if .Addons}}
---
apiVersion: app.undistro.io/v1alpha1
kind: DefaultPolicies
metadata:
  name: "defaultpolicies-{{.Name}}"
  namespace: {{.Namespace}}
  labels:
    undistro.io/move: ""
spec:
  clusterName: {{.Name}}
---
apiVersion: app.undistro.io/v1alpha1
kind: Observer
metadata:
  name: "undistro-observer-{{.Name}}"
  namespace: {{.Namespace}}
  labels:
    undistro.io/move: ""
spec:
  clusterName: {{.Name}}
  paused: false
{{- if .AuthEnabled}}
---
apiVersion: app.undistro.io/v1alpha1
kind: Identity
metadata:
  name: "undistro-identity-{{.Name}}"
  namespace: {{.Namespace}}
  labels:
    undistro.io/move: ""
spec:
  clusterName: {{.Name}}
  paused: false
  local: false
{{- end }}
{{- end }}