name: Tests

on:
  push:
    branches: ["*"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.6.2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go

      - name: Set up Node 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
        id: node

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Run chart-testing (lint)
        run: |
          helm repo add undistro https://registry.undistro.io/chartrepo/library
          helm repo add prometheus https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update
          ct lint --print-config --all --validate-chart-schema false --excluded-charts eck-operator --excluded-charts elasticsearch --excluded-charts kibana --excluded-charts fluentd

      - name: Get dependencies
        run: go mod download

      - name: Build UI
        working-directory: ./gui
        run: |
          yarn
          yarn build

      - name: Build CLI
        run: make cli

      - name: Build Manager
        run: make manager

      - name: Build AWS Init
        run: make aws-init

      - name: Test
        run: make test

      - name: Check GoReleaser config
        uses: goreleaser/goreleaser-action@v2
        with:
          args: check
